봉사 신청 기능 구현
team-aliens/DMS-Frontend pull request #103
Opened 2024-09-26 05:20 UTC by eejx0

## 개요
- 봉사 활동 추가
- 봉사 활동 수정
- 봉사 활동 삭제
- 봉사 활동 조회
- 봉사 활동 신청된 학생 조회
- 봉사 활동 신청 수락
- 봉사 활동 신청 거절
- 봉사 활동 신청 제외
- 봉사 현황 조회

## 이슈 번호
#102

2024-09-26 05:48 UTC, Juone2 requested changes
칭찬을 좋아하는 이으진을 위해.. 엄청 잘했고 고생했어 ㅎㅎ 컴포넌트 로직도 잘 분리하고 api 연동하는 로직도 잘 작성한 거 같네요 👍 리뷰 남겨준 거 확인 후 수정할 부분 수정하고 review request 걸어 주세용

++ 이번달 100커밋 넘는 거 뭐야 완전 열심히 하네 😆

2024-09-26 05:48 UTC, Juone2 commented on services/admin/src/apis/volunteers/index.ts
좋은데 이으진~~

2024-09-26 05:48 UTC, Juone2 commented on services/admin/src/apis/volunteers/response.ts
> +export interface getApplicationVolunteerStudentsResponse {
레전드 변수명 길이

2024-09-26 05:48 UTC, Juone2 commented on services/admin/src/components/modals/AddVolunteer.tsx
> +    console.log(volunteerData);
이거 지워 주세욘

2024-09-26 05:48 UTC, Juone2 commented on services/admin/src/components/volunteer/InfoCard.tsx
> +  };
이정도면 그냥 onClick함수 안에 해 줘도 될 듯?

2024-09-26 05:48 UTC, Juone2 commented on services/admin/src/pages/volunteer/Application.tsx
> +  }, []);
페이지가 마운트 됐을 때 데이터 받아오려고 이렇게 한 거 같은데, useQuery 사용하면 페이지가 마운트 됐을 때 실행 되니까 이렇게 굳이 불필요하게 useEffect 안 써 줘도 돼요! useQuery 사용하면 에러 처리도 같이 할 수 있으니까 이렇게 하는 거보다 훨씬 더 효율적이에요  다음부터 페이지가 마운트 되었을 때 데이터를 받아오고 싶을 때 useQuery 사용 해 보시면 좋을 듯 합니다 ㅎㅎ

2024-09-26 05:48 UTC, Juone2 commented on services/admin/src/components/modals/AddVolunteer.tsx
> +    }
로그 찍는 거보다 throw new Error로 에러 띄우는 게 더 좋을 거 같아요!!

2024-09-26 05:48 UTC, Juone2 commented on services/admin/src/components/volunteer/InfoCard.tsx
> +    }
상동

2024-09-26 05:48 UTC, Juone2 commented on services/admin/src/pages/volunteer/Application.tsx
> +    }
상동

2024-09-26 05:48 UTC, Juone2 commented on services/admin/src/pages/volunteer/Application.tsx
> +          ))}
👍👍

2024-09-26 05:48 UTC, Juone2 commented on services/admin/src/pages/volunteer/Detail.tsx
> +  }, [volunteerId]);
상동

2024-09-26 05:48 UTC, Juone2 commented on services/admin/src/pages/volunteer/index.tsx
> +  }, []);
상동

2024-09-26 07:11 UTC, eejx0 commented on services/admin/src/components/modals/AddVolunteer.tsx
> +    }
토스트로 띄우는것도 좋을 것 같은데.. 어때요??

2024-09-26 09:24 UTC, eejx0 commented on services/admin/src/pages/volunteer/Application.tsx
> +  }, []);
넵!

2024-09-27 02:51 UTC, Juone2 approved these changes

2024-09-27 02:51 UTC, Juone2 commented
신청 탭에 봉사 추가도 해 줘

2024-10-08 09:20 UTC, Juone2 approved these changes

2024-10-08 11:22 UTC, merged